version: '3.8'

services:
  apache:
    build: ./apache
    container_name: apache
    ports:
      - 9095:80
    volumes:
      - ./apache/static:/usr/local/apache2/htdocs/static
    depends_on:
      - python

  python:
    build: .
    container_name: python
    environment:
      PYTHONBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: CineApp
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: CineApp
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./Juegos.sql:/docker-entrypoint-initdb.d/Juegos.sql
    user: mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
