version: '3.8'

services:
  apache:
    build: ./apache
    container_name: apache2b
    ports:
      - 6102:80
    volumes:
      - ./apache/static:/var/www
    depends_on:
      - python
    networks:
      - backend

  python:
    build: .
    container_name: python2b
    environment:
      PYTHONBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: CineApp
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=8080
    volumes:
      - ./web:/app
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: mariadb2b
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: CineApp
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Juegos.sql:/docker-entrypoint-initdb.d/Juegos.sql
    user: mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin2b
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - 7102:80
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data:
